### PR TITLE
Update to version 1.0.1

### PR DESCRIPTION
**Pull request by dstansby**
An attempt to see what's going wrong with the CI, since the logs aren't available in all the older PRs.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by dstansby** [comment]
There's a couple of issues, but one seems to be the `pypy` builds taking issue with these lines:

https://github.com/astropy/astropy-healpix/blob/d116ecc3efb84bda71f5866b120abdc96a815446/astropy_healpix/_core.c#L17-L19

**Comment by astrofrog** [comment]
I had to fix this in PyERFA: https://github.com/liberfa/pyerfa/pulls?q=is%3Apr+is%3Aclosed+pypy - we should do something similar for astropy-healpix

**Comment by dstansby** [comment]
I've added patches to fix the build issues - not sure if it's best to do a release of 1.0.0 with these patches, then remove them in a later version, or skip 1.0.0 in conda, fix upstream, and do a release without any patches?

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by lpsinger** [comment]
Whatever you prefer. I was planning to do a release very soon anyway.

**Comment by dstansby** [comment]
If you don't mind doing a release with patches would be nice to do a release - the reason I got on to this was it's blocking sunpy from doing the Python 3.12 migration 😄 (via reproject doing a Python 3.12 migration)

**Comment by lpsinger** [comment]
> If you don't mind doing a release with patches would be nice to do a release - the reason I got on to this was it's blocking sunpy from doing the Python 3.12 migration 😄 (via reproject doing a Python 3.12 migration)

See https://github.com/astropy/astropy-healpix/pull/200.

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by dstansby** [comment]
Fab, I updated to version 1.0.1 and removed the patches, and all seems to have worked 🎉 I think this is good to merge now

**Review by lpsinger — APPROVED** [review]

**Comment by dstansby** [comment]
Looks like this is redundant now 1.0.2 has been released

**Pull request closed without merging**
